# 遗传算法参数
POPULATION_SIZE = 100
MAX_GENERATIONS = 1000
CROSSOVER_RATE = 0.85
MUTATION_RATE = 0.15
ELITISM_COUNT = 2
    
# 时间表约束权重
DEFAULT_SCORE = 1000
# 硬约束
LECTURER_CONFLICT_WEIGHT = 50
VENUE_CONFLICT_WEIGHT = 40
BATCH_CONFLICT_WEIGHT = 60
# 软约束
AVAILABILITY_WEIGHT = 30
    
# 其他配置
MAX_RETRIES = 100 # 最大重试次数
TIME_SLOTS = list(range(1,17))
DAYS = ['MO', 'TU', 'WE', 'TH', 'FR']