# 遗传算法参数
POPULATION_SIZE = 50
MAX_GENERATIONS = 1000
CROSSOVER_RATE = 0.85
MUTATION_RATE = 0.15
ELITISM_COUNT = 5
MAX_NO_IMPROVE = 50
TOURNAMENT_SIZE = 5
    
# 基础分数倍数
DEFAULT_SCORE_BASE = 300
TARGET_FITNESS_BASE = DEFAULT_SCORE_BASE / 100 * 99
MINIMUN_TARGET_BASE = DEFAULT_SCORE_BASE / 100 * 90
# 硬约束
LECTURER_CONFLICT_WEIGHT = 50 * 5
VENUE_CONFLICT_WEIGHT = 40 * 5
BATCH_CONFLICT_WEIGHT = 60 * 5
AVAILABILITY_WEIGHT = 30 * 5
# 软约束
SOFT_CONSTRAINTS_TINY = 3
SOFT_CONSTRAINTS_SMALL = 5
SOFT_CONSTRAINTS_MEDIUM = 10
SOFT_CONSTRAINTS_LARGE = 20
    
# 其他配置
MAX_RETRIES = 100 # 最大重试次数
TIME_SLOTS = list(range(1,17))
DAYS = ['MO', 'TU', 'WE', 'TH', 'FR']